version: "3.9"

services:
  frontend:
    container_name: frontend
    build: ./co2-emission-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app_network
      
  backend:
    container_name: backend
    build: ./co2-emission-backend
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    networks:
      - app_network
networks:
  app_network: